name: Continuous VPS with Tailscale

on:
  schedule:
    - cron: '*/330 * * * *'   # Every 5h30m
  workflow_dispatch:

jobs:
  vps-session:
    runs-on: ubuntu-latest
    timeout-minutes: 325   # Just under 5h30m

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Restore persistent data
        uses: actions/cache@v4
        with:
          path: .vps-data
          key: vps-data
          restore-keys: vps-data

      - name: Install Tailscale
        run: |
          sudo apt-get update
          sudo apt-get install -y tailscale
          sudo mkdir -p .vps-data

      - name: Start Tailscale
        run: |
          sudo tailscaled --state=.vps-data/tailscaled.state --socket=/tmp/tailscaled.sock &
          sleep 8
          sudo tailscale --socket=/tmp/tailscaled.sock up --authkey=${{ secrets.TS_KEY }} --hostname=biralo --reset

      - name: Show Tailscale IP
        run: sudo tailscale --socket=/tmp/tailscaled.sock ip

      - name: Save persistent data
        uses: actions/cache/save@v4
        with:
          path: .vps-data
          key: vps-data
