name: Continuous Persistent VPS

on:
  schedule:
    - cron: '30 */5 * * *'  # Every 5 hours 30 minutes
  workflow_dispatch:

jobs:
  vps-session:
    runs-on: ubuntu-latest
    timeout-minutes: 330  # 5 hours 30 minutes

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set hostname to DarkNodes
        run: |
          sudo hostnamectl set-hostname DarkNodes

      - name: Download VPS backup (if any)
        uses: actions/download-artifact@v4
        with:
          name: vps-backup
          path: ./backup
        continue-on-error: true

      - name: Install prerequisites
        run: |
          sudo apt update
          sudo apt install -y tmate curl unzip sudo net-tools neofetch

      - name: Install Tailscale official script
        run: |
          curl -fsSL https://tailscale.com/install.sh | sh

      - name: Restore backup files (safe)
        run: |
          if [ -f ./backup/backup.zip ]; then
            sudo unzip -o ./backup/backup.zip -d /
            echo "VPS backup restored"
          else
            echo "No backup found, starting fresh"
          fi

      - name: Restore Tailscale state (safe)
        run: |
          if [ -f ./backup/data/tailscaled.state ]; then
            sudo mkdir -p /var/lib/tailscale
            sudo cp -f ./backup/data/tailscaled.state /var/lib/tailscale/tailscaled.state
            sudo chown root:root /var/lib/tailscale/tailscaled.state
            sudo chmod 600 /var/lib/tailscale/tailscaled.state
            echo "Tailscale state restored"
          else
            echo "No Tailscale state found, will start fresh"
          fi

      - name: Start Tailscale
        run: |
          sudo pkill tailscaled || true
          sudo tailscaled &
          sleep 5
          sudo tailscale up --authkey ${{ secrets.TAILSCALE_AUTHKEY }} --hostname=DarkNodes || echo "Tailscale already up"
          echo "Current Tailscale IPs:"
          tailscale ip -4

      - name: Create user Darknodes with sudo
        run: |
          if ! id -u Darknodes >/dev/null 2>&1; then
            sudo useradd -m -s /bin/bash Darknodes
            echo "Darknodes:Darknodes" | sudo chpasswd
            sudo usermod -aG sudo Darknodes
            echo "Darknodes ALL=(ALL) NOPASSWD:ALL" | sudo tee /etc/sudoers.d/Darknodes
          fi

      - name: Start tmate session for SSH access
        uses: mxschmitt/action-tmate@v3

      - name: Show Tailscale IP and tmate info
        run: |
          echo "Tailscale IP:"
          tailscale ip -4 || echo "Tailscale IP not found"
          echo ""
          echo "tmate SSH session info:"
          if [ -S $HOME/.tmate.sock/ssh ]; then
            cat $HOME/.tmate.sock/ssh
          else
            echo "tmate socket not ready"
          fi

      - name: Keep VPS alive
        run: sleep 19800  # 5 hours 30 minutes

      - name: Backup VPS data and Tailscale state
        run: |
          sudo mkdir -p /opt/vps-backup/data
          # Backup Tailscale state
          if [ -f /var/lib/tailscale/tailscaled.state ]; then
            sudo cp -f /var/lib/tailscale/tailscaled.state /opt/vps-backup/data/
          fi
          # Backup any other important directories (add your paths if needed)
          # sudo cp -r /path/to/data /opt/vps-backup/data/
          sudo chown -R $USER:$USER /opt/vps-backup
          cd /opt/vps-backup
          zip -r backup.zip ./*

      - name: Upload VPS backup artifact
        uses: actions/upload-artifact@v4
        with:
          name: vps-backup
          path: /opt/vps-backup/backup.zip
