name: Persistent DarkNodes VPS with Tailscale (Auto-Restart)

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *" # every 6 hours (~5h30m)

jobs:
  vps:
    runs-on: ubuntu-latest
    timeout-minutes: 360 # 6 hours

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # Restore previous Tailscale state
      - name: Restore Tailscale state
        uses: actions/cache@v3
        id: tailscale-cache
        with:
          path: .vps-data/tailscale.state
          key: tailscale-state-${{ runner.os }}

      - name: Set hostname
        run: sudo hostnamectl set-hostname DarkNodes

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl wget iproute2 jq gnupg lsb-release

      - name: Install Tailscale
        run: |
          curl -fsSL https://pkgs.tailscale.com/stable/ubuntu/$(lsb_release -cs).gpg | sudo tee /usr/share/keyrings/tailscale-archive-keyring.gpg > /dev/null
          curl -fsSL https://pkgs.tailscale.com/stable/ubuntu/$(lsb_release -cs).list | sudo tee /etc/apt/sources.list.d/tailscale.list
          sudo apt-get update
          sudo apt-get install -y tailscale
          mkdir -p .vps-data

      - name: Start Tailscale
        run: |
          sudo tailscaled --state=$(pwd)/.vps-data/tailscale.state --socket=$(pwd)/.vps-data/tailscaled.sock --port 41641 &
          sleep 10
          if [ -f ".vps-data/tailscale.state" ]; then
            echo "Restoring previous Tailscale node..."
            sudo tailscale up --hostname=DarkNodes --accept-routes --accept-dns || true
          else
            echo "First run, using authkey..."
            sudo tailscale up --authkey=${{ secrets.TAILSCALE_AUTHKEY }} --hostname=DarkNodes --accept-routes --accept-dns
          fi

          # Save the current IP
          IP=$(tailscale ip -4)
          echo $IP > DarkNodes-Latest-IP.txt
          echo "$(date '+%Y-%m-%d %H:%M:%S') - $IP" >> DarkNodes-IP-Log.txt
          echo "Current Tailscale IP: $IP"

      - name: Upload IP logs
        uses: actions/upload-artifact@v3
        with:
          name: DarkNodes-Tailscale-IPs
          path: |
            DarkNodes-Latest-IP.txt
            DarkNodes-IP-Log.txt

      - name: Run VPS session for 5h30m
        run: |
          echo "VPS running with persistent Tailscale IP..."
          sleep 19800 # 5h30m in seconds

      - name: Backup Tailscale state
        if: always()
        run: |
          echo "Saving Tailscale state..."
          mkdir -p .vps-data
          cp -f .vps-data/tailscale.state .vps-data/tailscale.state

      - name: Auto-restart workflow
        if: always()
        run: |
          echo "Restarting workflow for continuous VPS..."
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/${{ github.workflow }}/dispatches \
            -d '{"ref":"main"}'
