name: Continuous Persistent VPS with Tailscale

on:
  workflow_dispatch:
  schedule:
    - cron: "*/330 * * * *" # every 5h30m

jobs:
  vps:
    runs-on: ubuntu-latest
    timeout-minutes: 330 # 5h30m

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # Restore previous Tailscale state
      - name: Restore Tailscale state
        uses: actions/cache@v3
        id: tailscale-cache
        with:
          path: .vps-data
          key: tailscale-state

      - name: Set hostname
        run: sudo hostname biralo

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl wget iproute2 jq

      - name: Install Tailscale
        run: |
          curl -fsSL https://pkgs.tailscale.com/stable/ubuntu/noble.gpg | sudo tee /usr/share/keyrings/tailscale-archive-keyring.gpg > /dev/null
          curl -fsSL https://pkgs.tailscale.com/stable/ubuntu/noble.list | sudo tee /etc/apt/sources.list.d/tailscale.list
          sudo apt-get update
          sudo apt-get install -y tailscale
          sudo mkdir -p .vps-data

      - name: Start Tailscale (persistent)
        run: |
          sudo tailscaled --state=.vps-data/tailscale.state --socket=.vps-data/tailscaled.sock --port 41641 &
          sleep 5
          if [ -f ".vps-data/tailscale.state" ]; then
            echo "Restoring previous Tailscale node..."
            sudo tailscale up --hostname=biralo --accept-routes --accept-dns
          else
            echo "First run, using authkey..."
            sudo tailscale up --authkey=${{ secrets.TAILSCALE_AUTHKEY }} --hostname=biralo --accept-routes --accept-dns
          fi

      - name: Run VPS Session (5h30m)
        run: |
          echo "VPS is running with persistent Tailscale IP..."
          sleep 19800 # 5h30m in seconds

      # Crash-proof backup of Tailscale state
      - name: Backup Tailscale state
        if: always()
        run: |
          echo "Saving Tailscale state..."
          mkdir -p .vps-data
          sudo tailscale bugreport --state=.vps-data/tailscale.state || true
